# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('final_estimate', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Story'),
        ),
    ]
