# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_evaluation_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together=set([('story', 'user')]),
        ),
    ]
